
export const RANDOMIZE_START = 'RANDOMIZE_START';
export const RANDOMIZE_COMPLETED = 'RANDOMIZE_COMPLETED';
export const RANDOMIZE_ERROR = 'RANDOMIZE_ERROR';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_COMPLETED = 'FETCH_USER_COMPLETED';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_VEHICLES_START = 'FETCH_VEHICLES_START';
export const FETCH_VEHICLES_COMPLETED = 'FETCH_VEHICLES_COMPLETED';
export const FETCH_VEHICLES_ERROR = 'FETCH_VEHICLES_ERROR';

export const CREATE_VEHICLE_START = 'CREATE_VEHICLE_START';
export const CREATE_VEHICLE_COMPLETED = 'CREATE_VEHICLE_COMPLETED';
export const CREATE_VEHICLE_ERROR = 'CREATE_VEHICLE_ERROR';

export const FETCH_PASSAGES_START = 'FETCH_PASSAGES_START';
export const FETCH_PASSAGES_COMPLETED = 'FETCH_PASSAGES_COMPLETED';
export const FETCH_PASSAGES_ERROR = 'FETCH_PASSAGES_ERROR';

export const CREATE_PASSAGE_START = 'CREATE_PASSAGE_START';
export const CREATE_PASSAGE_COMPLETED = 'CREATE_PASSAGE_COMPLETED';
export const CREATE_PASSAGE_ERROR = 'CREATE_PASSAGE_ERROR';

export const FETCH_BILLING_FOR_DATES_START = 'FETCH_BILLING_FOR_DATES_START';
export const FETCH_BILLING_FOR_DATES_COMPLETED = 'FETCH_BILLING_FOR_DATES_COMPLETED';
export const FETCH_BILLING_FOR_DATES_ERROR = 'FETCH_BILLING_FOR_DATES_ERROR';



